### ISSUE TITLE
[bug]: Source Installer: EnvironmentFileNotFound environment.yml

### ISSUE THREAD

**Issue by SylversVolpe** [invoke-ai/InvokeAI#1885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

After running the Source Installer for a while, this error pops up and stops the installation: 

"EnvironmentFileNotFound: 'G:\InvokeAI\environment.yml' file not found"

### Screenshots

![image](https://user-images.githubusercontent.com/38909283/206767894-19dd3c28-38fd-4017-95da-bcc020017d71.png)

### Contact Details

sylvervolpe@gmail.com

**Comment by SylversVolpe** [comment]
Resolved itself when I tried again after a reboot.

**Comment by bjgilberd** [comment]
I'm having the same issue - have tried rebooting as per @SylversVolpe but still getting the same error.  Even tried creating an empty file by that name - but it's complaining that the file is empty.
