### ISSUE TITLE
[bug]: Windows 11 - update.bat reports that "v.2.2.5" or "latest" are both not "known branch name or tag."

### ISSUE THREAD

**Issue by Turkinolith** [invoke-ai/InvokeAI#2194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What happened?

When running the v2.2.4 to v2.2.5 update.bat I get a `"'!INVOKE_AI_VERSION!' is not a known branch name or tag"` regardless of the arguments I put into the command.

This occurs when double clicking the update.bat, when running it from the command line, and when running it from the command line as admin.

**Comment by CreationStory** [comment]
check dir is a repo

**Comment by lstein** [comment]
Updating is temporarily disabled while we do the release. It will be possible to update later today.

**Comment by tarungupta83** [comment]
You can update the release by installing the 2.2.5 -rc9 zip installer on the same folder where your older version is installed. This will not re download the model. Rather it will update only the UI components. After installation you should be able to see Model Manager. Right now Stable Diffusion 2.1 gives an error.

**Comment by lstein** [comment]
2.2.5 is released and the update script should work now. Let me know if you experience any issues with it.

**Comment by Turkinolith** [comment]
> 2.2.5 is released and the update script should work now. Let me know if you experience any issues with it.

Still getting " '{}' is not a known branch name or tag." 
for: default of "latest", v2.2.5, and 2.2.5

might not have fully propagated yet, will try again in a few hours.

**Comment by Turkinolith** [comment]
I was able to follow @tarungupta83 's suggestion and use the installer to "update" things.
the update script still did not function for me as of 5 minutes ago.
Will leave the bug here for tracking if anyone else encounters, but feel free to close as my specific instance is resolved.

**Comment by paccocino** [comment]
I have the same error, 
using 2.5.5
starting update.bat worked the last times, but since end of march i only get
"latest is not a known branch"
and it cancels
Tried the last 5 days...

**Comment by ecentinela** [comment]
Same here. Could it be a Python compatibility issue? My computer just updated to 3.11.3

**Comment by mediashock** [comment]
I have the same issue.

**Comment by lstein** [comment]
Updating from versions earlier than 2.3 is not supported, unfortunately.
You will need to download the zip installer from the release page and run
it, allowing it to install into your existing `invokeai` directory.
