### ISSUE TITLE
[bug]: AttributeError: module 'diffusers.models.attention' has no attribute 'CrossAttention'

### ISSUE THREAD

**Issue by ghost** [invoke-ai/InvokeAI#3182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

2.3.4

### What happened?

It was installing without problems, when it was time to run it gave that error.

### Screenshots

![image](https://user-images.githubusercontent.com/124453184/231520941-af432eb0-b29b-4b9f-9789-59dc60e5e9c9.png)
![image](https://user-images.githubusercontent.com/124453184/231521038-07e510ba-4968-401a-b880-3a4ae9a69956.png)

### Additional context

It happens when I try to run it.

**Comment by byebye758** [comment]
I also encountered the same error when using invokeai-configure in manual installation mode on my Mac Mini M2.

**Comment by AviDTechnion** [comment]
This seems global.
maybe they moved it to module cross_attention.py ?

**Comment by gardunorr** [comment]
Same problem !

**Comment by RogueTabletop** [comment]
I'm also having this Issue.

**Comment by reicou** [comment]
same problem here

**Comment by Dragostini** [comment]
Same problem on fresh install

**Comment by MetaverseJosh** [comment]
> I solved it by downloading the Source code (zip) file, then changing the diffusers version to 0.14.0 at the pyproject.toml file, and then going to the installer folder, and generating a new installer file by running the create_installer.sh script

I am trying to do what you do but when I try to recompile the installer I get this error:
create_installer.sh: line 14: python: command not found

**Comment by FrogBucket** [comment]
Enter the venv and pip install the older diffuser version, there is no need to run the create_installer script.

**Comment by BrunoBieri** [comment]
I've the same problem on fresh install on Windows 11 Pro (22H2 - 22621.1555).

**Comment by Void2258** [comment]
The new version of diffusers has a breaking bug in it, and the version pinning failed to work. Issue has been identified and is being worked on. for now `pip install --upgrade --force-reinstall diffusers==0.14` in the dev console (option 8) will fix things.

**Comment by MetaverseJosh** [comment]
Same problem fresh install with fresh python 10.9 or 10.10.

**Comment by pryadchenko** [comment]
Thus us because of recent update of diffusers. Just downgrade it:
`python -m pip install diffusers==0.14.0`

**Comment by meandnano** [comment]
> This is because of recent update of diffusers. Just downgrade it: `python -m pip install diffusers==0.14.0`

Did it in the invokeai's venv and it seemed to help. No issues so far.

The full fix:
```
. .venv/bin/activate
python -m pip install diffusers==0.14.0
```

**Comment by romandesign** [comment]
> > This is because of recent update of diffusers. Just downgrade it: `python -m pip install diffusers==0.14.0`
> 
> Did it in the invokeai's venv and it seemed to help. No issues so far.
> 
> The full fix:
> 
> ```
> . .venv/bin/activate
> python -m pip install diffusers==0.14.0
> ```

I tried that but got the same error

**Comment by romandesign** [comment]
> > This is because of recent update of diffusers. Just downgrade it: `python -m pip install diffusers==0.14.0`
> 
> Did it in the invokeai's venv and it seemed to help. No issues so far.
> 
> The full fix:
> 
> ```
> . .venv/bin/activate
> python -m pip install diffusers==0.14.0
> ```

I did it and it didn't work. Perhaps I'm not doing anything correctly, I don't understand what the first line means. Second command run OK and did bunch of things, but I still get the same error. I have deleted the old InvokeAI installation and I'm trying to install it from scratch to d:\InvokeAI\ but I get the same error.

**Comment by blessedbob** [comment]
Bump, got this same error  
![image](https://user-images.githubusercontent.com/120555656/231600062-d6a9ecd5-d29d-444f-85b0-7e1fdc07b01d.png)

**Comment by romandesign** [comment]
OK, so here's a full fix for those who like me don't know how to use Python properly.
1.  After the error occurs, run CMD and go to the installation folder into .venv\Scripts directory and run activate.bat that should be there.
2. Then you will see the (.venv) prompt. In that prompt run `python -m pip install diffusers==0.14.0` and you will see a message about version 15 uninstalled and 14 installed.
3. Then try installing InvokeAI again and it should work. At least I got past the error point without any problem.

**Comment by SoyPro12** [comment]
1) install
2) <error> press any key
3) closing installer
4) run invoke.bat
5) 8 - dev console
6) pip install --upgrade --force-reinstall diffusers==0.14.0
7) close that window
8) run invoke.bat once again
9) 7. re-run the configure script to fix a broken install
Credit: StAlKeR7779 on the Invoker Discord

**Comment by Bacon-Tech** [comment]
I did try to update the code to use what the deprecated warning said and that got me past this error during installation but then after trying to load the tool I ran into another error `module 'os' has no attribute 'fork'`.

So I just decided to do a clean install of the latest alpha and we will see how that goes.

if anyone else wants to try below is what I did.

in the `cross_attention_control.py` file I change line 450:

`class InvokeAIDiffusersCrossAttention(diffusers.models.attention.CrossAttention, InvokeAICrossAttentionMixin):`

to:

`class InvokeAIDiffusersCrossAttention(diffusers.models.attention_processor.Attention, InvokeAICrossAttentionMixin):`

**Comment by xDylite** [comment]
> 1. install
> 
>     2. press any key
> 
>     3. closing installer
> 
>     4. run invoke.bat
> 
>     5. 8 - dev console
> 
>     6. pip install --upgrade --force-reinstall diffusers==0.14.0
> 
>     7. close that window
> 
>     8. run invoke.bat once again
> 
>     9. 7 re-run the configure script to fix a broken install
> 
> 
> Credit: StAlKeR7779 on the Invoker Discord

Took a couple of tries but this indeed works :D

**Comment by lstein** [comment]
New release to fix this issue: https://github.com/invoke-ai/InvokeAI/releases/tag/v2.3.4.post1

**Comment by Void2258** [comment]
If this has been fixed should this issue be closed?

**Comment by BrunoBieri** [comment]
Tested the new release 2.3.4.post1 on Windows 11 Pro and the installation worked for me where I previously encountered that issue.

**Comment by gardunorr** [comment]
Yes, 


Thank you 


___________________________________ 

----- Mail original -----

De: "Void2258" ***@***.***> 
À: "invoke-ai/InvokeAI" ***@***.***> 
Cc: "gardunorr" ***@***.***>, "Comment" ***@***.***> 
Envoyé: Vendredi 14 Avril 2023 16:21:34 
Objet: Re: [invoke-ai/InvokeAI] [bug]: AttributeError: module 'diffusers.models.attention' has no attribute 'CrossAttention' (Issue #3182) 



If this has been fixed should this issue be closed?

**Comment by lstein** [comment]
Yes, it is fixed. I just left the issue open for a bit so that people could
see the message at the bottom that the issue was resolved.

**Comment by cinemapara** [comment]
**On macbook m2 ventura** i still get AttributeError: module 'diffusers.models.attention' has no attribute 'CrossAttention'
I tried diffusers-0.15.0 and diffusers-0.14.0
I was using https://github.com/invoke-ai/InvokeAI/releases/tag/v2.3.4.post1

**Comment by lstein** [comment]
> **On macbook m2 ventura** i still get AttributeError: module 'diffusers.models.attention' has no attribute 'CrossAttention' I tried diffusers-0.15.0 and diffusers-0.14.0 I was using https://github.com/invoke-ai/InvokeAI/releases/tag/v2.3.4.post1

Could you provide the steps needed to reproduce the error?

**Comment by XDUWQ** [comment]
```
from diffusers.models.attention_processor import Attention
```

**Comment by ruofanliu0129** [comment]
Just simply try "pip install diffusers<=0.16.0", which works for me.

**Comment by JY9087** [comment]
> This is because of recent update of diffusers. Just downgrade it: `python -m pip install diffusers==0.14.0`

It works ! Thank you !
