### ISSUE TITLE
[bug]: Cant start Invoke after 3.0.1rc1

### ISSUE THREAD

**Issue by etha302** [invoke-ai/InvokeAI#4051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24gb

### What version did you experience this issue on?

3.0.1rc1

### What happened?

This is the error i am getting after updating to 3.0.1rc1, i tried both automatic and manual update(under developer console), and it installs just fine, but then refuses to start.

****An exception has occurred: C:\Users\user\invokeai\models\core\convert\CLIP-ViT-bigG-14-laion2B-39B-b160k is missing
== STARTUP ABORTED ==
** One or more necessary files is missing from your InvokeAI root directory **
** Please rerun the configuration script to fix this problem. **
** From the launcher, selection option [7]. **
** From the command line, activate the virtual environment and run "invokeai-configure --yes --skip-sd-weights" **
Press any key to continue...****

### Screenshots

![2023-07-28_191809](https://github.com/invoke-ai/InvokeAI/assets/139644787/2b9619c0-f170-475f-b854-ab8ac86f8348)

**Comment by lstein** [comment]
Have you tried rerunning the configure script by selection option [7] in the launcher?

This will download and install new files that are needed for SDXL rendering.

**Comment by etha302** [comment]
> Have you tried rerunning the configure script by selection option [7] in the launcher?
> 
> This will download and install new files that are needed for SDXL rendering.

it did install some things and succeeded. but sadly broke everything even further, now i cant open developer console or fix broken install.
![23](https://github.com/invoke-ai/InvokeAI/assets/139644787/6dbb53ac-5edb-4ee0-a185-25875831741a)

**Comment by 5chlupp** [comment]
Same for me on Mac OS after using the Update Option number 9. Number 7 dit not fix it.

 For a more attractive experience, please install the 'dialog' utility using your package manager. **

> What would you like to do?
> 1: Generate images using the browser-based interface
> 2: Explore InvokeAI nodes using the command-line interface
> 3: Run textual inversion training
> 4: Merge models (diffusers type only)
> 5: Download and install models
> 6: Change InvokeAI startup options
> 7: Re-run the configure script to fix a broken install
> 8: Open the developer console
> 9: Update InvokeAI
> 10: Command-line help
> Q: Quit
> 
> Please enter 1-10, Q: [1] 1
> 
> 
> 
> 
> 
> 
> 
> Generate images with a browser-based interface
> >> patchmatch.patch_match: INFO - Compiling and loading c extensions from "/Users/XXX/Pictures/AI-Kunst/InvokeAI300/.venv/lib/python3.10/site-packages/patchmatch".
> >> patchmatch.patch_match: ERROR - patchmatch failed to load or compile (Command 'make clean && make' returned non-zero exit status 2.).
> >> patchmatch.patch_match: INFO - Refer to https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/ for installation instructions.
> [2023-07-29 17:21:56,869]::[InvokeAI]::INFO --> Patchmatch not loaded (nonfatal)
> /Users/XXX/Pictures/AI-Kunst/InvokeAI300/.venv/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
>   warnings.warn(
> 
> An exception has occurred: /Users/XXX/Pictures/AI-Kunst/InvokeAI300/models/core/convert/CLIP-ViT-bigG-14-laion2B-39B-b160k is missing
> == STARTUP ABORTED ==
> ** One or more necessary files is missing from your InvokeAI root directory **
> ** Please rerun the configuration script to fix this problem. **
> ** From the launcher, selection option [7]. **
> ** From the command line, activate the virtual environment and run "invokeai-configure --yes --skip-sd-weights" **
> Press any key to continue...
>

**Comment by 5chlupp** [comment]
a new installation  with the 3.0.1 install.sh in a new folder brings the same error message as after the update from 3.0.0.

Number 7 does not fix it like before either.
The CL interface seems to be functional. 

I did not understand this.

> ** From the command line, activate the virtual environment and run "invokeai-configure --yes --skip-sd-weights".

_______________________

>  ** For a more attractive experience, please install the 'dialog' utility using your package manager. **
> 
> What would you like to do?
> 1: Generate images using the browser-based interface
> 2: Explore InvokeAI nodes using the command-line interface
> 3: Run textual inversion training
> 4: Merge models (diffusers type only)
> 5: Download and install models
> 6: Change InvokeAI startup options
> 7: Re-run the configure script to fix a broken install
> 8: Open the developer console
> 9: Update InvokeAI
> 10: Command-line help
> Q: Quit
> 
> Please enter 1-10, Q: [1] 1
> 
> 
> 
> 
> 
> 
> 
> Generate images with a browser-based interface
> >> patchmatch.patch_match: INFO - Compiling and loading c extensions from "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI301/.venv/lib/python3.11/site-packages/patchmatch".
> >> patchmatch.patch_match: ERROR - patchmatch failed to load or compile (Command 'make clean && make' returned non-zero exit status 2.).
> >> patchmatch.patch_match: INFO - Refer to https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/ for installation instructions.
> [2023-07-29 18:33:35,074]::[InvokeAI]::INFO --> Patchmatch not loaded (nonfatal)
> /Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI301/.venv/lib/python3.11/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
>   warnings.warn(
> 
> An exception has occurred: /Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI301/models/core/convert/CLIP-ViT-bigG-14-laion2B-39B-b160k is missing
> == STARTUP ABORTED ==
> ** One or more necessary files is missing from your InvokeAI root directory **
> ** Please rerun the configuration script to fix this problem. **
> ** From the launcher, selection option [7]. **
> ** From the command line, activate the virtual environment and run "invokeai-configure --yes --skip-sd-weights" **
> Press any key to continue...
>

**Comment by 5chlupp** [comment]
I have the same bug with **v3.0.1post3**.
I also tried to install it completely fresh with the new installer.
I also tried to update my existing installation with 9 and then repair it with 7.


> Generate images with a browser-based interface
> >> patchmatch.patch_match: INFO - Compiling and loading c extensions from "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI301 /.venv/lib/python3.11/site-packages/patchmatch".
> >> patchmatch.patch_match: ERROR - patchmatch failed to load or compile (Command 'make clean && make' returned non-zero exit status 2.).
> >> patchmatch.patch_match: INFO - Refer to https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/ for installation instructions.
> [2023-07-30 20:27:49,239]::[InvokeAI]::INFO --> Patchmatch not loaded (nonfatal)
> /Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI301 /.venv/lib/python3.11/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
>   warnings.warn(
> 
> An exception has occurred: /Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI301 /models/core/convert/CLIP-ViT-bigG-14-laion2B-39B-b160k is missing
> == STARTUP ABORTED ==
> ** One or more necessary files is missing from your InvokeAI root directory **
> ** Please rerun the configuration script to fix this problem. **
> ** From the launcher, selection option [7]. **
> ** From the command line, activate the virtual environment and run "invokeai-configure --yes --skip-sd-weights" **
> Press any key to continue...

**Comment by jonebarker** [comment]
Having the same issue with fresh install of 3.0.1 post3.  As an experiment, I duplicated the clip-vit-large-patch14 folder and named it "CLIP-ViT-bigG-14-laion2B-39B-b160k" and the error went away.  Then I got another error:  "\invokeai\models\core\convert\sd-vae-ft-mse is missing".  Confused now.

**Comment by 5chlupp** [comment]
Hello. 
With **3.0.2rc1** it is still broken.
I have installed it completely fresh and I have updated an existing installation.
I also tried number 7 again. 

Are there other ways I can help or what I can do to fix it? :-(

> An exception has occurred: /Volumes/X/invoke/models/core/convert/CLIP-ViT-bigG-14-laion2B-39B-b160k is missing

**Comment by jonebarker** [comment]
I'm not at my PC right now, but I just saw a potential solution on another forum. about deleting invokeai/venv/pyvenv.cfg.  I'll test it later today, or someone can try sooner.

Source:  https://forums.unraid.net/topic/130913-guide-invokeai-a-stable-diffusion-toolkit-docker/page/4/

**Comment by 5chlupp** [comment]
@jonebarker Feel free to try it out. Under Mac OS, it is no longer possible to update invoke ai or anything else.
<img width="682" alt="Bildschirmfoto 2023-08-09 um 17 27 45" src="https://github.com/invoke-ai/InvokeAI/assets/58439006/6d914bda-ea9b-4edf-93dc-81e83edd4046">

**Comment by jonebarker** [comment]
> @jonebarker Feel free to try it out. Under Mac OS, it is no longer possible to update invoke ai or anything else.
> 

That sucks.. If you need to work on MacOS asap,  you can try Automatic 1111 or Diffusion Bee until InvokeAi provides a fix.

**Comment by 5chlupp** [comment]
@jonebarker Thank you! <3 I have both programmes running.
I'm curious and keeping my fingers crossed for you!

**Comment by 5chlupp** [comment]
I found the folders on Hugging Face and downloaded them, but then stopped at the error message.  

> An exception has occurred: /Volumes/lnt7/invoke/models/core/convert/stable-diffusion-2-clip is missing

because the core folder has been about 225MB and not over 20GB.
But there seems to be a lot missing in the folder.
If I go by the error message.

**Comment by brainbent** [comment]
Had the same message after upgrading from 2.3.5 to 3.2. Fixed by downloading the 3.2 installer, and then reinstalling in place... x

**Comment by quantum909** [comment]
Is there a solution for this Problem? Tried various installers etc. The problem persists
