### ISSUE TITLE
[bug]: MacOSX/M1 Flux workflow 5.0.0: TypeError: BFloat16 is not supported on MPS

### ISSUE THREAD

**Issue by michaeljanich** [invoke-ai/InvokeAI#6991]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### GPU model

Mac M1PRO

### GPU VRAM

64GB

### Version number

5.0.0

### Browser

Safari

### Python dependencies

2024-09-30 18:17:29,099]::[InvokeAI]::ERROR --> Error while invoking session d89a3487-6d47-47c4-a615-81c1b00afe3f, invocation 334ced98-d3a4-4e20-b1e6-5130a4af608a (flux_denoise): BFloat16 is not supported on MPS
[2024-09-30 18:17:29,099]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/Users/massa/AI/.venv/lib/python3.11/site-packages/invokeai/app/services/session_processor/session_processor_default.py", line 129, in run_node
    output = invocation.invoke_internal(context=context, services=self._services)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/massa/AI/.venv/lib/python3.11/site-packages/invokeai/app/invocations/baseinvocation.py", line 290, in invoke_internal
    output = self.invoke(context)
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/massa/AI/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/massa/AI/.venv/lib/python3.11/site-packages/invokeai/app/invocations/flux_denoise.py", line 98, in invoke
    latents = self._run_diffusion(context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/massa/AI/.venv/lib/python3.11/site-packages/invokeai/app/invocations/flux_denoise.py", line 115, in _run_diffusion
    flux_conditioning = flux_conditioning.to(dtype=inference_dtype)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/massa/AI/.venv/lib/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusion/conditioning_data.py", line 47, in to
    self.clip_embeds = self.clip_embeds.to(device=device, dtype=dtype)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BFloat16 is not supported on MPS

[2024-09-30 18:17:29,107]::[InvokeAI]::INFO --> Graph stats: d89a3487-6d47-47c4-a615-81c1b00afe3f
                          Node   Calls   Seconds  VRAM Used
             flux_model_loader       1    0.001s     0.000G
             flux_text_encoder       1    0.000s     0.000G
                      rand_int       1    0.000s     0.000G
                  flux_denoise       1    0.004s     0.000G
TOTAL GRAPH EXECUTION TIME:   0.005s
TOTAL GRAPH WALL TIME:   0.006s
RAM used by InvokeAI process: 4.11G (+0.000G)
RAM used to load models: 0.00G
RAM cache statistics:
   Model cache hits: 0
   Model cache misses: 0
   Models cached: 0
   Models cleared from cache: 0
   Cache high water mark: 0.00/0.00G

### What happened

TypeError: BFloat16 is not supported on MPS

### What you expected to happen

Render image

### How to reproduce the problem

Any standard FLUX1.0 workflow (Flux Dev Quant, Flux Schnell Quant) to standard invoke with prompt.

### Additional context

Happens every time.

**Comment by michaeljanich** [comment]
5.0.2 has the same problems.

**Comment by Vargol** [comment]
If we assume the endpoint of this is to get flux working, then you'll need to upgrade torch to a nightly version, that should l resolve the error your getting, but you'll bump into another error about float64 not being supported, you'll need to edit 
that reference in `invokeai/backend/flux/math.py` from float64 to float32.

That should get the full versions of Flux.1 [dev] and Flux.1 [schnell] working.

Quantised versions, you're out of luck, the library used to support those isn't compatible with MacOS (and I believe Windows, AMD GPU's and Intel GPU's too ,some of that might be out of date)

**Comment by Aedant13** [comment]
I'm getting this error when trying to use flux : RuntimeError: "arange_mps" not implemented for 'BFloat16'

Is there a fil I should modify? I updated to torch nightly.

**Comment by Vargol** [comment]
Torch nightly should work, unless the release of 2.5.0 has changes what's in the nightly release,  the fix was merged into the repository as https://github.com/pytorch/pytorch/pull/136754 and I've used nightly to work around this for a few weeks now.

Having said that, I created a pull release for working around that issue using PyTorch 2.4.1 which was approved a few minutes ( https://github.com/invoke-ai/InvokeAI/pull/7113 ) ago so hopefully the next release will have that in. 
If you bring that in a suggest that into grab the code from https://github.com/invoke-ai/InvokeAI/pull/7140 which is currently waiting approval as that'll stop the t5encoder being loaded in as float32 on Macs.

**Comment by michaeljanich** [comment]
I still can't use Flux on Mac even in 5.4.0:

```
[2024-11-05 08:17:00,624]::[InvokeAI]::INFO --> Patchmatch initialized
[2024-11-05 08:17:02,135]::[InvokeAI]::INFO --> Using torch device: MPS
[2024-11-05 08:17:02,641]::[uvicorn.error]::INFO --> Started server process [16036]
[2024-11-05 08:17:02,641]::[uvicorn.error]::INFO --> Waiting for application startup.
[2024-11-05 08:17:02,642]::[InvokeAI]::INFO --> InvokeAI version 5.4.0

```

Result: black images. No error messages.

**Comment by Vargol** [comment]
Have you set precision tp bfloat16 ?

**Comment by michaeljanich** [comment]
No I have not. Where do I do that?

**Comment by Vargol** [comment]
In your invokeai.yanl file...
mine looks like 
```
# Internal metadata - do not edit:
schema_version: 4.0.2

# Put user settings here - see https://invoke-ai.github.io/InvokeAI/features/CONFIGURATION/:
outputs_dir: /Users/Vargol/invokeai/outputs
vram:  1
device: mps
precision: bfloat16
```

**Comment by michaeljanich** [comment]
That works (using invokeai.yaml). Many thanks! 🙏

**Comment by yourmomdatestedcruz** [comment]
Not to dig this up but I'm having issues following the "steps" in here.

I'm trying to FLUX dev and getting the same `BFloat16 is not supported` on MPS issue -- so I try to upgrade torch, but when I try to do that it only goes up to 2.2.2, and refuses to "find" a version above that, despite 2.5.0 and now 2.5.1 being released.

Any ideas on what the issue might be?

**Comment by Vargol** [comment]
> Not to dig this up but I'm having issues following the "steps" in here.
> 
> I'm trying to FLUX dev and getting the same `BFloat16 is not supported` on MPS issue -- so I try to upgrade torch, but when I try to do that it only goes up to 2.2.2, and refuses to "find" a version above that, despite 2.5.0 and now 2.5.1 being released.
> 
> Any ideas on what the issue might be?

Sounds like you're still on a oldish version of InvokeAI (torch 2.4.1 as default came be a release or two including rc's after Flux was added to InvokeAI)  and  pip is hitting a hard requirement for a lower version torch, maybe from torchvision.
Try 
```
pip uninstall torch torchvision
pip install torch==2.4.1 torchvision==0.18.1
```
I do not recommend torch 2.5.1 it has a massive issue with MPS , using way more memory and  30% slower. That was 'fixed' in the nightlies  which use a touch more memory that 2.4.1 but are ~ 10% faster than even 2.4.1
if you want to try a nightly try
```
pip uninstall torch torchvision
pip install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cpu
```

**Comment by yourmomdatestedcruz** [comment]
@Vargol thanks for your reply! I just tried both things (in the invokeai venv, as I assumed that was needed) and still no luck:

When I try this:
```
pip uninstall torch torchvision
pip install torch==2.4.1 torchvision==0.18.1
```
My terminal returns this: 
```
ERROR: Could not find a version that satisfies the requirement torch==2.4.1 (from versions: 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==2.4.1
```

I'm not sure why but it seems to think that the most recent version is 2.2.2 - is there a way I can force it to check elsewhere? or could I point it to install a package I'd downloaded manually instead, and make it accept that its version is higher than 2.2.2?


When trying the nightly route with:
```
pip uninstall torch torchvision
pip install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cpu
```

I get an error as well:
```
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
```

**Comment by Vargol** [comment]
What version of MacOS are you on ? I suspect you're going to be on a 13.x

**Comment by Vargol** [comment]
Are you on Intel or did you use Brew from before it was properly supported Apple Silicon, Brew encouraged people to set their terminal to run via X86 emulation which makes everything run from terminal install the x86 versions and torch 2.2.2 was the last version that supported x86.

I you still have the logs from pip installing 2.2.2 look for a line like this (only for 2.2.2)
Using cached torch-2.5.1-cp311-none-macosx_11_0_arm64.whl (63.9 MB)
Using cached torchvision-0.20.1-cp311-cp311-macosx_11_0_arm64.whl (1.8 MB)

and see if its installing  ...arm64.whl  or  something intel-ish like x86_64.whl

**Comment by yourmomdatestedcruz** [comment]
I think that's it - I installed Brew on an intel machine and just migrated that with everything to Apple Silicon.

I ran `brew config` and it definitely looks intel-ish: it reports that the OS is `macOS: 15.1-x86_64`

I'll see if I can change that in place or just re-install; though that might take a while as I have a few things using Brew.


In the meantime, I'm trying to run this in [Stability Matrix](https://github.com/LykosAI/StabilityMatrix) -- It's downloading the model now so we'll see in a bit but in looking at the python packages in the image, it looks like it has torch 2.4.1; so fingers crossed.


I'll report back.

**Comment by yourmomdatestedcruz** [comment]
Update - I can confirm that my issue is that my version of brew got carried through to my Apple Silicon system from my Intel based Macbook Pro; and so that limits my version of pytorch to 2.2.2 as @Vargol mentioned.

My solution currently is to run InvokeAI through Stability Matrix - It's very simple and I'm not mad at all to not be running it "natively".
@Vargol I'm not sure about the hows/whos/wheres/whens but it may be worth noting that as an installation method. It effectively runs containerized with full access to Apple Silicon GPUs.

The fix I'd have to carry out to run it natively in case anyone would like to have confirmation in the future, would be to uninstall brew, and all the packages that brew installed and then reinstall brew on the Apple Silicon chip to get the correct version, then re-install from there. That's not the most effective solution for me at the moment so I'll carry on using Stability Matrix.
