### ISSUE TITLE
[bug]: error when i change proportion from 1:1 to any else

### ISSUE THREAD

**Issue by tvortsa** [invoke-ai/InvokeAI#7348]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

rtx3060

### GPU VRAM

6Gb

### Version number

5.4.1

### Browser

chrome

### What happened

I try to change proportions from 1:1 to 3:4, 3:2, 16:9 etc. i cant do this, i get error:
```
Input should be a multiple of 16
Path: body.batch.graph.nodes.sd3_denoise:AGG3eD3Ly9.sd3_denoise.height
```

### What you expected to happen

i wish just change proportion not only 1:1

**Comment by psychedelicious** [comment]
This issue was resolved in [v5.4.2](https://github.com/invoke-ai/InvokeAI/releases/tag/v5.4.2).

**Comment by Crono141** [comment]
This bug is still present in 5.4.3. SD3.5 only works in 1:1. Any other aspect ratio results in this error, even when ensuring the outputs are multiples of 16.
