### ISSUE TITLE
[bug]: Failed to load some Z-image loras in 6.10.0rc1

### ISSUE THREAD

**Issue by mweldon** [invoke-ai/InvokeAI#8707]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### Install method

Invoke's Launcher

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

3060

### GPU VRAM

12

### Version number

6.10.0rc1

### What happened

I've tried a few of this guy's Loras for Z-image and they error when I try to load them in version 10. Here is one example (SFW) https://civitai.com/models/2240502/zit-cutout-dress-01. He has several other Loras and they don't all throw the same error. This one fails as well (slightly NSFW link) https://tinyurl.com/3426bxwk.

### What you expected to happen

Expected the lora to load properly and be selectable during Z-image gen.

### How to reproduce the problem

Download the lora. Load it from a specified directory from the models page. Observe error.

### Discord username

BSunshine

**Comment by Pfannkuchensack** [comment]
#8709

**Comment by lstein** [comment]
This issue should be fixed in RC2, which is due very soon.

**Comment by lstein** [comment]
Please confirm if the LoRAs Now load properly in 6.10.0rc2

**Comment by mweldon** [comment]
The cutout dress Lora works correctly, however the second link that I posted above, the tiny URL, still does not identify as a Lora. The model loads but I am not able to use it as a lora.

**Comment by Pfannkuchensack** [comment]
i will check that.
